language: ruby
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
    services:
      - mongodb
    after_success:
      - coveralls
  - rvm: 2.4.1
    env:
      - LABEL=unit_tests
    services:
      - mongodb
  - rvm: 2.3.4
    env:
      - LABEL=unit_tests
    services:
      - mongodb
  - rvm: 2.2.7
    env:
      - LABEL=unit_tests
    services:
      - mongodb
