language: ruby
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x scriptname database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
    after_success:
      - coveralls
  - rvm: 2.4.1
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x scriptname database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
  - rvm: 2.3.4
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x scriptname database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
  - rvm: 2.2.7
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x scriptname database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
  - rvm: 2.4.1
    env:
      - LABEL=docker_build_tests
    services:
      - docker
    script:
      - docker-compose build