language: ruby
sudo: false
dist: trusty
before_install: gem update --system
addons:
  postgresql: "9.6"
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
    after_success:
      - coveralls
  - rvm: 2.5.0
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
  - rvm: 2.3.6
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
  - rvm: 2.2.9
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - chmod u+x database/init-user-db-travis.sh
      - database/init-user-db-travis.sh
  - rvm: 2.5.0
    env:
      - LABEL=docker_build_tests
    services:
      - docker
    script:
      - docker-compose build