language: ruby
matrix:
  include:
  - rvm: ruby-head
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - createdb ssh_observatory
      - createuser sshobs --createdb --no-password
      - psql ssh_observatory < database/schema.sql
    after_success:
      - coveralls
  - rvm: 2.4.1
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - createdb ssh_observatory
      - createuser sshobs --createdb --no-password
      - psql ssh_observatory < database/schema.sql
  - rvm: 2.3.4
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - createdb ssh_observatory
      - createuser sshobs --createdb --no-password
      - psql ssh_observatory < database/schema.sql
  - rvm: 2.2.7
    env:
      - LABEL=unit_tests
    services:
      - postgres
    before_script:
      - createdb ssh_observatory
      - createuser sshobs --createdb --no-password
      - psql ssh_observatory < database/schema.sql
  - rvm: 2.4.1
    env:
      - LABEL=docker_build_tests
    services:
      - docker
    script:
      - docker-compose build