version: '2'
services:
  database:
    image: mongo:latest
    container_name: database
    volumes:
      - mongodb
    restart: always
  api:
    build:
      context: .
      dockerfile: ./docker/api
    command: /app/bin/ssh_scan_api
    ports:
      - 8000:8000
    environment:
      - sshscan.database.host=database
    container_name: api
    links:
      - database
      - worker
    restart: always
  worker:
    build:
      context: .
      dockerfile: ./docker/api
    environment:
      - sshscan.api.host=api
    command: /app/bin/ssh_scan_worker
    container_name: worker
    restart: always