version: '2'
services:
  database:
    image: mongo:latest
    container_name: database
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    networks:
      - default
    volumes:
      - ./data/db:/data/db
    restart: always
  api:
    build:
      context: .
      dockerfile: ./docker/api
    command: /app/bin/ssh_scan_api
    ports:
      - 8000:8000
    environment:
      - sshscan.api.bind=api
      - sshscan.database.host=database
      - sshscan.worker.token=d63920d7-82d1-4781-a6f9-369528c1f179
    container_name: api
    links:
      - database
      - worker
    networks:
      - default
    restart: always
  worker:
    build:
      context: .
      dockerfile: ./docker/worker
    environment:
      - sshscan.api.host=api
      - sshscan.worker.token=d63920d7-82d1-4781-a6f9-369528c1f179
    command: /app/bin/ssh_scan_worker
    container_name: worker
    networks:
      - default
    restart: always