version: '2'
services:
  database:
    build:
      context: .
      dockerfile: ./docker/database
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: ./docker/api
    ports:
      - 8000:8000
    links:
      - database
    environment:
      - SSH_SCAN_API_BIND=api
    networks:
      - default
    restart: always
    depends_on:
      - "database"
    stdin_open: true
    tty: true
    working_dir: /app
    command: ["/app/docker/wait-for-it.sh", "database:5432", "--", "/app/bin/ssh_scan_api"]