version: '2'
services:
  base:
    build:
      context: .
      dockerfile: ./docker/base
  database:
    build:
      context: .
      dockerfile: ./docker/database
    # Uncomment below if you would like direct access to the DB for debugging/troubleshooting, this is not enabled by default for safety reasons
    # ports:
    #   - 5432:5432
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    networks:
      - default
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: ./docker/api
    ports:
      - 8000:8000
    environment:
      - SSHAPIBIND=api
      - SSHSCANDATABASEENV=development
    links:
      - database
    networks:
      - default
    restart: always
    depends_on:
      - "base"
      - "database"
    stdin_open: true
    tty: true
    working_dir: /app
    command: ["/app/docker/wait-for-it.sh", "database:5432", "--", "/app/bin/ssh_scan_api"]
  worker:
    build:
      context: .
      dockerfile: ./docker/worker
    environment:
      - SSHSCANDATABASEENV=development   
    links:
      - database
    networks:
      - default
    depends_on:
      - "base"
      - "database"
      - "api"
    restart: always
    working_dir: /app
    command: ["/app/docker/wait-for-it.sh", "api:8000", "--", "/app/bin/ssh_scan_worker"]