version: '2'
services:
  database:
    build:
      context: .
      dockerfile: ./docker/database
    ports:
      - 5432:5432
    networks:
      - default
    restart: unless-stopped
  api:
    build:
      context: .
      dockerfile: ./docker/api
    ports:
      - 8000:8000
    environment:
      - sshscan.api.bind=api
      - sshscan.database.host=database
      - sshscan.worker.token=EXAMPLE_TOKEN_CHANGE_ME
    links:
      - database
    networks:
      - default
    restart: always
    depends_on:
      - "database"
    command: ["/app/docker/wait-for-it.sh", "database:5432", "--", "/app/bin/ssh_scan_api"]
  worker:
    build:
      context: .
      dockerfile: ./docker/worker
    environment:
      - sshscan.api.host=api
      - sshscan.worker.token=EXAMPLE_TOKEN_CHANGE_ME
    command: /app/bin/ssh_scan_worker
    links:
      - api
    networks:
      - default
    depends_on:
      - "api"
    restart: always
    command: ["/app/docker/wait-for-it.sh", "api:8000", "--", "/app/bin/ssh_scan_worker"]